basePath: /api/v1
definitions:
  request.ShortenUrlRequest:
    properties:
      custom_short:
        type: string
      expiration:
        type: string
      url:
        type: string
    type: object
  response.ResponseErrorModel:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.ShortenUrlResponse:
    properties:
      custom_short:
        type: string
      expiration:
        type: string
      url:
        type: string
    type: object
host: localhost
info:
  contact: {}
  description: This is the API for GoShorty, a URL shortening service
  title: GoShorty API
  version: 0.1.0
paths:
  /url/{short}:
    get:
      consumes:
      - application/json
      description: Resolve a shortened URL to its original URL
      parameters:
      - description: Short to resolve
        in: path
        name: short
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Redirect to original URL
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErrorModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ResponseErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResponseErrorModel'
      summary: Resolve a shortened URL
      tags:
      - URL
  /url/shorten:
    post:
      consumes:
      - application/json
      description: Shorten a given URL and return the shortened version
      parameters:
      - description: URL to be shortened
        in: body
        name: shortenUrl
        required: true
        schema:
          $ref: '#/definitions/request.ShortenUrlRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Shortened URL
          schema:
            $ref: '#/definitions/response.ShortenUrlResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErrorModel'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ResponseErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResponseErrorModel'
      summary: Shorten a URL
      tags:
      - URL
schemes:
- https
swagger: "2.0"
