services:
  api: 
    build: 
      context: .
    image: goshorty-api:local
    container_name: api
    environment:
      REDIS_ADDRESS: "redis:6379"
      PORT: "8080"
      DB_CONNECTION_STRING: "host=user_db port=5432 user=postgres password=password dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      user_db:
        condition: service_healthy
  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  user_db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    container_name: user_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5