basePath: /
definitions:
  models.ShortenRequest:
    properties:
      expiration:
        type: string
      short:
        type: string
      url:
        type: string
    type: object
  models.ShortenResponse:
    properties:
      expiration:
        type: string
      short:
        type: string
      url:
        type: string
    type: object
  routes.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  routes.RateLimitExceededResponse:
    properties:
      error:
        type: string
      rate_limit_reset:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample URL shortener server.
  title: GoShorty API
  version: "1.0"
paths:
  /{url}:
    get:
      description: Resolve a shortened URL to its original URL
      parameters:
      - description: Shortened URL
        in: path
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Moved Permanently
          schema:
            type: string
        "404":
          description: URL not found
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
      summary: Resolve a shortened URL
      tags:
      - URL
  /api/v1:
    post:
      consumes:
      - application/json
      description: Shorten a given URL with an optional custom short and expiration
        time
      parameters:
      - description: URL Shorten Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ShortenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ShortenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/routes.RateLimitExceededResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.ErrorResponse'
      summary: Shorten a URL
      tags:
      - URL
swagger: "2.0"
