name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test-build-push:
    name: Test, Build, And Upload Docker Image
    runs-on: ubuntu-latest
    environment: 
      name: 'DEV' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '>=1.23.0'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.ECR_WORKFLOW_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: Push-To-ECR

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Set TIMESTAMP
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build Image
        run: docker build -t goshorty:latest .

      - name: Tag And Push Docker Image
        run: |
          docker tag goshorty:latest ${{ secrets.ECR_LOGIN_SERVER }}:latest
          docker tag goshorty:latest ${{ secrets.ECR_LOGIN_SERVER }}:${{ env.TIMESTAMP }}
          docker push ${{ secrets.ECR_LOGIN_SERVER }}:latest
          docker push ${{ secrets.ECR_LOGIN_SERVER }}:${{ env.TIMESTAMP }}

      - name: Logout from ECR
        run: docker logout ${{ secrets.ECR_LOGIN_SERVER }}